# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/audette',
                'doc_host': 'https://frenio.github.io',
                'git_url': 'https://github.com/frenio/audette',
                'lib_path': 'audette'},
  'syms': {'audette.core': {'audette.core.foo': ('core.html#foo', 'audette/core.py')}}}
